# Generated by Django 2.0.1 on 2018-02-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=50)),
                ('admin', models.BooleanField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=500)),
                ('created_at', models.FloatField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
